
GET http://localhost:3000/user

###
GET http://localhost:3000/user/1

###
POST http://localhost:3000/user
Content-Type: application/json

{
    "username":"JohnDoe",
    "email":"johndoe@gmail.com",
    "phone": "0123456789"
}

###
PUT http://localhost:3000/user/18
Content-Type: application/json

{
    "username":"JohnDoe",
    "email":"johndoe@gmail.com",
    "phone": "0123456789"
}

###
DELETE  http://localhost:3000/user/17
