
GET http://localhost:3000/user


###
POST http://localhost:3000/user
Content-Type: application/json

{
    "username":"JohnDoe",
    "email":"johndoe@gmail.com",
    "phone": "0123456789"
}

###
DELETE  http://localhost:3000/user/1
